"""Typed architecture and benchmark specs."""

from .common import BenchmarkBudgetSpec, BenchmarkRunManifest, DeviceRuntimeSpec, JsonlCorpusSpec, SeedSpec
from .mini_moe import (
    MiniMoeArchitectureSpec,
    MiniMoeBackboneSpec,
    MiniMoeDispatchMode,
    MiniMoeDispatchSpec,
    MiniMoeLayerSchedule,
    MiniMoeLayerScheduleKind,
    MiniMoeLayerSchedulePreset,
    MiniMoeObservabilitySpec,
    MiniMoePreset,
    MiniMoeRouterSpec,
    MiniMoeRuntimeSpec,
    MiniMoeStackSpec,
    MiniMoeSurfaceSpec,
    OneShotRouterSpec,
    RecurrentPreExpertRouterSpec,
    ResolvedMiniMoeLayout,
)
from .path1 import (
    BYTE_LEVEL_PAD_TOKEN,
    BYTE_LEVEL_VOCAB_SIZE,
    DEFAULT_PATH1_MODEL_SHAPE,
    HybridAttentionLayerRole,
    Path1BaselineMatrix,
    Path1ModelShape,
    Path1VariantKind,
    Path1VariantSpec,
    PrimitiveExecutionProfile,
    PrimitiveNormMode,
    PrimitiveProfile,
    PrimitiveReadoutMode,
    PrimitiveResidualMode,
    PrimitiveWrapperMode,
    ReferenceSsmProfile,
    phase1_attention_only_variant,
    phase1_baseline_matrix,
    phase1_primitive_variant,
    phase1_reference_ssm_variant,
)
